<?php

class Insertar_proyecto
{
    function registro_proyecto($id_uusario, $nombre, $descripcion, $fecha)
    {
        $temp = 0;
        try {
            include_once("../../CONTROLADOR/key.php");
            $k = new key();
            include_once("../../MODELO/conect.php");
            $mysql_object = new conect();

            $statementHandle = $mysql_object->connect()->prepare("INSERT INTO proyectos(ID_PROYECTO,ID_USUARIO,NOMBRE_PROYECTO, DESCRIPCION, FECHA_MODIFICACION) VALUES (?,?,?,?,?)");
            if ($statementHandle->execute(array(null, $id_uusario, $nombre, $descripcion, $fecha))) {
                include_once("../../MODELO/Proyectos/Consultar_proyecto.php");
                $obj_proyectos = new Consultar_proyecto();
                $datos_proyecto = $obj_proyectos->selectProjectbyNameAndDesc($nombre, $descripcion);
                $id_proyecto = $datos_proyecto[0][0];
                include_once("../../MODELO/Calificacion_proyectos/Insertar_calificacion_proyectos.php");
                $obj_calificacion = new Insertar_calificacion_proyectos();
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE I"), $k->enc('Introducción'), $k->enc("Es la presentación sintética y concisa del informe de investigación, la cual explica la descripción del problema, el alcance, las limitaciones, la metodología o procedimientos que se utilizarán, pero sin adelantar resultados ni llegar a concluir, asimismo, pueden citarse agradecimientos institucionales. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE II"), $k->enc('Planteamiento del problema'), $k->enc("El planteamiento del problema es el punto de partida de la investigación (Rodríguez Gómez, et. al., 2009). Este apartado permite afinar y estructurar formalmente la idea de investigación, desarrollándolo a partir de los siguientes puntos: Identificación y delimitación del problema, valoración del problema y formulación de este. Los tres elementos deben ser capaces de guiar una investigación de manera pertinente y con posibilidad de prueba empírica (Tello, 2011). (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE III"), $k->enc('Justificación'), $k->enc("Permite evidenciar las razones que llevan a la construcción de la investigación en curso, indica el para qué o por qué debe efectuarse, así mismo los beneficios que se derivan del proceso de investigación, considerando la conveniencia, relevancia social, implicaciones prácticas, valor teórico y utilidad metodológica. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE IV"), $k->enc('Hipótesis'), $k->enc("Indican lo que estamos buscando (se puede tener una, dos o varias hipótesis) y pueden definirse como explicaciones tentativas del fenómeno investigado formuladas a manera de proposiciones, estas no necesariamente son verdaderas; son proposiciones tentativas acerca de las relaciones entre dos o más variables y se apoyan en conocimientos organizados y sistematizados. En el caso de las investigaciones cualitativas presentar supuestos de investigación (Hernández, et al, 2014). (No deberá exceder a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE V"), $k->enc('Objetivo general'), $k->enc("Es el enunciado claro y preciso de lo que se pretende alcanzar con el proyecto, el cual debe redactarse iniciando con verbo en infinitivo, además de ser alcanzable, medible o cuantificable, temporal y relevante."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE VI"), $k->enc('Objetivos secundarios'), $k->enc("Se refieren a los aspectos que se desea estudiar, o a los resultados intermedios que se espera obtener para dar respuesta final al problema. (Estos pueden ser opcionales)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE VII"), $k->enc('Tipo de investigación'), $k->enc("Una primera tipificación casi clásica de la investigación puede ser en función del nivel de profundidad del conocimiento manejado. Por ejemplo, de menor a mayor conocimiento, así como de la relación del objeto de estudio con el investigador. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE VIII"), $k->enc('Marco teórico'), $k->enc("Es un compendio escrito del análisis de artículos, libros y otros documentos actualizados que describen el estado pasado y actual del conocimiento sobre el problema de estudio (Hernández, et al, 2014) que contribuye a documentar cómo el proyecto agrega valor a la literatura existente. Podrá referirse y/o citarse, literatura mayor a 5 años, cuando sea el caso que tenga información relevante e imprescindible para el proyecto y no comprenda la mayoría de las referencias acotadas. El marco teórico constituye el conjunto teórico y conceptual a través del cual se podrán analizar e interpretar los datos obtenidos, además, en el caso de la elaboración de prototipos constituye los recursos teóricos que fundamentan su elaboración. Deberá contener como mínimo 10 referencias bibliográficas. (No deberá exceder las tres cuartillas)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE IX"), $k->enc('Descripción del desarrollo e implementación del prototipo'), $k->enc("El objetivo del apartado es describir con detalle el proceso secuencial y los recursos utilizados durante la ejecución del proyecto, alineado al proceso de investigación científica o metodología aplicada. (No deberá exceder a cuatro cuartillas)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE X"), $k->enc('Propuesta de valor del prototipo'), $k->enc("Se trata de la razón por la que los clientes o usuarios optan por este prototipo, producto o servicio en lugar de otras opciones. Ésta consiste en la manera en que en un futuro próximo se pueda convertir en un negocio con valor para un segmento específico a través de una mezcla de distintos elementos. Estos pueden ser cuantitativos como precio o rapidez o bien, cualitativos como diseño o experiencia (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XI"), $k->enc('Estudio de viabilidad para la implementación del prototipo'), $k->enc("Son las circunstancias, y sugiere la probabilidad de que pueda hacerse con éxito (si la iniciativa, idea, propuesta o proyecto es o no realizable) es decir es su capacidad para finalizar satisfactoriamente, entregando los resultados esperados con la iniciativa. Analizar esta cualidad antes de la etapa de planificación sirve como guía para impulsar la toma de decisiones desde la comprensión integral de los parámetros del proyecto, los objetivos a alcanzar y los factores de riesgo.2 (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XII"), $k->enc('Estudio de factibilidad técnica y financiera (costots) para su producción e implementación'), $k->enc("Comprende el análisis y operaciones de los materiales utilizados y los demás análisis relacionados con el diseño y el funcionamiento del prototipo planteado. En cuanto a la factibilidad financiera considera el análisis de los costos y gastos en que se incurrirá para la producción, contra la cuantificación de los beneficios económicos que se obtendrían con su implementación o precio de venta. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XIII"), $k->enc('Impacto social, ecológico, tecnológico y/o desarrollo sustentable'), $k->enc("El impacto social considera los logros y beneficios que aporta a la comunidad. El desarrollo sustentable es un proceso integral que exige a los distintos actores de la sociedad, compromisos y responsabilidades en la aplicación del modelo económico, político, ambiental y social, así como en los patrones de consumo que determinan la calidad de vida. El impacto tecnológico considera los alcances y beneficios que las nuevas tecnologías están dando a la sociedad actual en todos los ámbitos. Para competir en mercados nacionales y extranjeros, el sector productivo debe incorporar la sustentabilidad en sus operaciones, relaciones con los trabajadores y la comunidad. En cuanto al impacto ambiental se refiere al conjunto de estudios y/o análisis técnicos que permiten valorar los efectos o consecuencias que puede causar sobre el medio ambiente o entorno ecológico o ecosistema en la ejecución, utilización o implementación de este prototipo. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XIV"), $k->enc('Estrategia para la protección de la propiedad intelectual del prototipo'), $k->enc("Es el proceso sistematizado en el que se conjuntan los derechos protegidos; los mecanismos de protección de los activos intangibles o tangibles. El Derecho de Propiedad Intelectual es una rama del Derecho Público y tiene por objeto la protección de las creaciones de la mente, tales como invenciones, obras literarias y artísticas, símbolos, nombres e imágenes que se utilizan en el comercio. La propiedad intelectual es protegida a través de la propiedad industrial y los derechos de autor. El Instituto Mexicano de la Propiedad Intelectual (IMPI) tiene atribuciones para fomentar y proteger la innovación a través del sistema de propiedad industrial, así como atender el uso ilegal de los derechos de propiedad intelectual. Este proceso inicia con la presentación de una solicitud de “declaración administrativa” que puede ser de: nulidad, caducidad, cancelación, infracción y declaratoria de notoriedad o fama de marcas. En este apartado se mostrará las estrategias y avances en la protección intelectual o de marca de su prototipo. (Se deberá limitar a una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XV"), $k->enc('Análisis de resultados'), $k->enc("Después de haber reunido la información, es necesario describir los hallazgos o resultados obtenidos; estos se podrán presentar a través de cuadros (tablas) y figuras (gráficas, impresiones de pantalla, fotografías, diagramas, mapas conceptuales, planos, etc.), incluyéndose en el cuerpo del trabajo los más relevantes, los demás se incluyen en los anexos. Van acompañados de una descripción analítica y explicativa de los hallazgos, para destacar los aspectos de mayor importancia y facilitar la comprensión de los resultados en forma gráfica; así como, explicar la técnica utilizada para el análisis de resultados (Hernández, et al, 2014). En este punto se pretende dar una explicación e interpretación de los resultados obtenidos, por medio del análisis de la información obtenida, recuperando los conceptos presentados en el marco teórico para interpretar los datos y resultados obtenidos. (No exceder a tres cuartillas)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XVI"), $k->enc('Conclusiones'), $k->enc("Constituyen la presentación de los hallazgos y sugerencias sobresalientes del proyecto. Deben ser específicos, concretos, sencillos, además de relacionarse con el planteamiento del problema, los objetivos planteados y la hipótesis formulada. (Máximo una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XVII"), $k->enc('Bibliografía'), $k->enc("Un estudio de investigación sin bibliografía carece de valor intelectual, porque no hay un soporte dentro de la comunidad científica que lo fundamente; por lo tanto, con mayor facilidad puede ser puesto en tela de juicio, ya que todo conocimiento tiene sus antecedentes. La bibliografía deberá presentarse en formato APA 7ª edición (American Phychological Association, 2020). (Máximo una cuartilla)."), 0, 0));
                $obj_calificacion->registro_precalificacion_proyecto(array(null, $id_proyecto, $k->enc("BLOQUE XVIII"), $k->enc('Anexos'), $k->enc("Son agregados que se colocan al final del proyecto, están compuestos por cuadros y figuras que pueden ser importantes para fortalecer el informe de investigación. Se debe hacer mención de ellos en el cuerpo del trabajo de acuerdo al orden en que fueron citados. (Máximo tres cuartillas)."), 0, 0));

                echo json_encode(array('result' => 1));
            } else
                echo json_encode(array('result' => 0));

        } catch (PDOException $e) {
            echo json_encode(array('result' => 0));
        }
        return $temp;
    }
}